name: Deployment
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      frontend: ./v2
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
        working-directory: ${{env.frontend}}
      - name: Build page
        run: npm run build
        working-directory: ${{env.frontend}}
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        # working-directory: ${{env.frontend}}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: master # deploying branch

