name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev


jobs:
  setup-build-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      frontend: ./v2
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          npm ci
          npm deploy